package com.example.xavier.lab_viajesbuses.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BUSES".
 */
public class buses {

    private String matricula;
    private String marca;
    private String modelo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public buses() {
    }

    public buses(String matricula) {
        this.matricula = matricula;
    }

    public buses(String matricula, String marca, String modelo) {
        this.matricula = matricula;
        this.marca = marca;
        this.modelo = modelo;
    }

    public String getMatricula() {
        return matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
