package com.example.xavier.lab_viajesbuses.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.xavier.lab_viajesbuses.dao.buses;
import com.example.xavier.lab_viajesbuses.dao.viajes;

import com.example.xavier.lab_viajesbuses.dao.busesDao;
import com.example.xavier.lab_viajesbuses.dao.viajesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig busesDaoConfig;
    private final DaoConfig viajesDaoConfig;

    private final busesDao busesDao;
    private final viajesDao viajesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        busesDaoConfig = daoConfigMap.get(busesDao.class).clone();
        busesDaoConfig.initIdentityScope(type);

        viajesDaoConfig = daoConfigMap.get(viajesDao.class).clone();
        viajesDaoConfig.initIdentityScope(type);

        busesDao = new busesDao(busesDaoConfig, this);
        viajesDao = new viajesDao(viajesDaoConfig, this);

        registerDao(buses.class, busesDao);
        registerDao(viajes.class, viajesDao);
    }
    
    public void clear() {
        busesDaoConfig.getIdentityScope().clear();
        viajesDaoConfig.getIdentityScope().clear();
    }

    public busesDao getBusesDao() {
        return busesDao;
    }

    public viajesDao getViajesDao() {
        return viajesDao;
    }

}
