package com.example.xavier.lab_viajesbuses.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.xavier.lab_viajesbuses.dao.viajes;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VIAJES".
*/
public class viajesDao extends AbstractDao<viajes, Long> {

    public static final String TABLENAME = "VIAJES";

    /**
     * Properties of entity viajes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Matricula_bus = new Property(1, String.class, "matricula_bus", false, "MATRICULA_BUS");
        public final static Property Destino = new Property(2, String.class, "destino", false, "DESTINO");
        public final static Property Pasajeros = new Property(3, String.class, "pasajeros", false, "PASAJEROS");
    };

    private DaoSession daoSession;


    public viajesDao(DaoConfig config) {
        super(config);
    }
    
    public viajesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIAJES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MATRICULA_BUS\" TEXT," + // 1: matricula_bus
                "\"DESTINO\" TEXT," + // 2: destino
                "\"PASAJEROS\" TEXT);"); // 3: pasajeros
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIAJES\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, viajes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String matricula_bus = entity.getMatricula_bus();
        if (matricula_bus != null) {
            stmt.bindString(2, matricula_bus);
        }
 
        String destino = entity.getDestino();
        if (destino != null) {
            stmt.bindString(3, destino);
        }
 
        String pasajeros = entity.getPasajeros();
        if (pasajeros != null) {
            stmt.bindString(4, pasajeros);
        }
    }

    @Override
    protected void attachEntity(viajes entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public viajes readEntity(Cursor cursor, int offset) {
        viajes entity = new viajes( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // matricula_bus
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // destino
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // pasajeros
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, viajes entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMatricula_bus(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDestino(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPasajeros(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(viajes entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(viajes entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBusesDao().getAllColumns());
            builder.append(" FROM VIAJES T");
            builder.append(" LEFT JOIN BUSES T0 ON T.\"MATRICULA_BUS\"=T0.\"MATRICULA\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected viajes loadCurrentDeep(Cursor cursor, boolean lock) {
        viajes entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        buses buses = loadCurrentOther(daoSession.getBusesDao(), cursor, offset);
        entity.setBuses(buses);

        return entity;    
    }

    public viajes loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<viajes> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<viajes> list = new ArrayList<viajes>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<viajes> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<viajes> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
